######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 29 15:05:56 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += $$PWD/main.cpp
