######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 29 16:37:12 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += color.h vec.h \
    shape.h
