######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 29 16:37:12 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

HEADERS += \
    $$PWD/vec.h \
    $$PWD/shape.h \
    $$PWD/muti_shape.h \
    $$PWD/color.h \
    $$PWD/util.h

SOURCES += \
    $$PWD/util.cpp

