######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 25 14:31:22 2018
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS +=  -std=c++11

# Input
HEADERS += color.h intersect.h shader.h svpng.inc
SOURCES += intersect.cpp plot_plus.cpp shader.cpp
